Repository bounswe/2021SpringGroup1, pull requests merged in 2021-12, with the labels that each got.

#188 Backend Integration is almost completed
  Web/src/App.js
  Web/src/components/LoginForm.js
  Web/src/navigation/Navigation.js
  Web/src/screens/allCommunitiesPage.js
  Web/src/screens/communityPage.js
  Web/src/screens/landingPage.js
  Web/src/screens/myCommunitiesPage.js
  Web/src/screens/myPosts.js
  Web/src/store/actions/authAction.js
  Web/src/store/actions/communityAction.js
  Web/src/store/actions/constants.js
  Web/src/store/actions/homeAction.js
  Web/src/store/actions/profileAction.js
  Web/src/store/reducers/authReducer.js
Labels: Type: Enhancement, Priority: High, Platform: Frontend

#195 Implementing User Home Feed , Searching Communities and changes on test.py
  cmpe451/protopost/models.py
  cmpe451/protopost/tests.py
  cmpe451/protopost/urls.py
  cmpe451/protopost/views.py
Labels: Platform: Backend

#196 I have made some major changes on Post Cards, Post Template Creation.…
  Web/package.json
  Web/src/App.js
  Web/src/components/card/MaterialUICard.js
  Web/src/components/card/SideCard.js
  Web/src/screens/allCommunitiesPage.js
  Web/src/screens/communityPage.js
  Web/src/screens/createCommunity.js
  Web/src/screens/createPostPage.js
  Web/src/screens/createPostTemplate.js
  Web/src/screens/landingPage.js
  Web/src/screens/myCommunitiesPage.js
  Web/src/screens/myPosts.js
  Web/src/utils/methods.js
  Web/yarn.lock
Labels: Type: Enhancement, Priority: Medium, Status: In Progress, Platform: Frontend, Review

#199 Image display on posts fixed and application name and logo added.
  Web/public/index.html
  Web/src/components/card/MaterialUICard.js
Labels: Type: Enhancement, Priority: Medium, Status: In Progress, Platform: Frontend

#194 Mobile create post template feature
  cmpe451-mobile/App.js
  cmpe451-mobile/app/screens/CommunityScreen.js
  cmpe451-mobile/app/screens/CreatePostTemplateScreen.js
  cmpe451-mobile/app/screens/PostScreen.js
  cmpe451-mobile/app/screens/UserCommunitiesScreen.js
  cmpe451-mobile/app/screens/UserHome.js
  cmpe451-mobile/app/screens/UserPostsScreen.js
  cmpe451-mobile/package-lock.json
  cmpe451-mobile/package.json
Labels: Type: Enhancement, Priority: High, Platform: Android

#206 Now user can create post templates and user can list post templates o…
  Web/src/components/card/MaterialUICard.js
  Web/src/screens/createPostTemplate.js
  Web/src/screens/myPosts.js
  Web/src/store/actions/communityAction.js
  Web/src/store/actions/constants.js
  Web/src/store/reducers/communityReducer.js
Labels: Type: Enhancement, Priority: Medium, Status: Revision Needed, Platform: Frontend

#219 Field Names added to post cards. Some minor changes added.
  Web/src/components/SignUpForm.js
  Web/src/components/SignUpLogin.css
  Web/src/components/card/MaterialUICard.js
  Web/src/components/navbar/SideBar.js
  Web/src/screens/myPosts.js
Labels: Type: Enhancement, Status: In Progress, Platform: Frontend

#220 Added post searching method in community
  cmpe451/protopost/urls.py
  cmpe451/protopost/views.py
Labels: Platform: Backend

#236 Implented core funtionality of FilterPosts endpoint
  cmpe451/protopost/models.py
  cmpe451/protopost/serializers.py
  cmpe451/protopost/urls.py
  cmpe451/protopost/views.py
Labels: Platform: Backend

#237 Adding User Profile endpoint
  cmpe451/protopost/urls.py
  cmpe451/protopost/views.py
Labels: Type: Enhancement, Priority: Medium, Status: Revision Needed, Platform: Backend
