Repository bounswe/2021SpringGroup1, pull requests merged in 2021-11, with the labels that each got.

#133 Model Update and Register/Login Functions
  .gitignore
  cmpe451/protopost/home.py
  cmpe451/protopost/models.py
  cmpe451/protopost/register.py
  cmpe451/protopost/urls.py
Labels: Platform: Backend

#139 Sidebar was added
  Web/package.json
  Web/public/index.html
  Web/src/App.js
  Web/src/components/navbar/SiderBar.js
  Web/src/navigation/Navigation.js
  Web/src/screens/bootstrap.js
  Web/yarn.lock
Labels: Priority: High, Review

#143 Added REST API implementaions and Swagger Schema Views
  .gitignore
  cmpe451/cmpe451/settings.py
  cmpe451/cmpe451/urls.py
  cmpe451/protopost/home.py
  cmpe451/protopost/models.py
  cmpe451/protopost/serializers.py
  cmpe451/protopost/tests.py
  cmpe451/protopost/urls.py
  cmpe451/protopost/views.py
Labels: Platform: Backend

#156 create new community page was created for design
  Web/src/DATABASE.js
  Web/src/components/navbar/SideBar.js
  Web/src/navigation/Navigation.js
  Web/src/screens/createCommunity.js
  Web/src/screens/myCommunitiesPage.js
Labels: Type: Enhancement, Priority: High, Platform: Frontend

#159 I put necessary functions to Redux
  Web/src/store/actions/authAction.js
  Web/src/store/actions/communityAction.js
  Web/src/store/actions/constants.js
  Web/src/store/actions/formData.js
  Web/src/store/actions/profileAction.js
  Web/src/store/reducers/auth.js
  Web/src/store/reducers/authReducer.js
  Web/src/store/reducers/communityReducer.js
  Web/src/store/reducers/profileReducer.js
  Web/src/store/store.js
Labels: Type: Enhancement, Priority: High, Platform: Frontend

#161 Create Community page improved.
  Web/src/screens/allCommunitiesPage.js
  Web/src/screens/communityPage.js
  Web/src/screens/createCommunity.js
  Web/src/screens/createPostPage.js
  Web/src/screens/createPostTemplate.js
  Web/src/screens/home.js
  Web/src/screens/landingPage.js
  Web/src/screens/myCommunitiesPage.js
  Web/src/screens/myPosts.js
Labels: Type: Enhancement, Priority: High, Platform: Frontend

#164 Multiple API calls implemented, style improvements made
  cmpe451-mobile/app/screens/AllCommunitiesScreen.js
  cmpe451-mobile/app/screens/CommunityScreen.js
  cmpe451-mobile/app/screens/LoginScreen.js
  cmpe451-mobile/app/screens/RegisterScreen.js
  cmpe451-mobile/app/screens/UserCommunitiesScreen.js
  cmpe451-mobile/app/screens/WelcomeScreen.js
  cmpe451-mobile/app/service/axios_client_service.js
  cmpe451-mobile/package-lock.json
  cmpe451-mobile/package.json
Labels: Platform: Android

#168 List user communities API call fixed
  cmpe451-mobile/app/screens/AllCommunitiesScreen.js
  cmpe451-mobile/app/screens/CommunityScreen.js
  cmpe451-mobile/app/screens/LoginScreen.js
  cmpe451-mobile/app/screens/UserCommunitiesScreen.js
  cmpe451-mobile/app/service/axios_client_service.js
  cmpe451-mobile/requirements.txt
Labels: Platform: Android
