Repository bounswe/2021SpringGroup1, pull requests merged in 2022-01, with the labels that each got.

#243 Delete Post endpoint
  cmpe451/protopost/urls.py
  cmpe451/protopost/views.py
Labels: Type: Enhancement, Priority: Medium, Platform: Backend

#242 Google Maps API added to post cards and Post creation page.
  Web/package.json
  Web/src/components/card/MaterialUICard.js
  Web/src/components/googleMaps.js
  Web/src/screens/createPostPage.js
  Web/yarn.lock
Labels: Type: Enhancement, Priority: Medium, Status: Completed, Platform: Frontend

#245 Number and video data fields are added.
  Web/package.json
  Web/src/components/card/MaterialUICard.js
  Web/src/screens/createPostPage.js
  Web/src/screens/createPostTemplate.js
  Web/yarn.lock
Labels: Type: Enhancement, Priority: Medium, Status: Completed, Platform: Frontend

#248 Added UpdatePost endpoint and vadification methods for DataFields
  cmpe451/protopost/serializers.py
  cmpe451/protopost/urls.py
  cmpe451/protopost/views.py
Labels: Priority: High, Platform: Backend

#254 Selection data type added to post template, post page and post cards.
  Web/src/components/card/MaterialUICard.js
  Web/src/screens/createPostPage.js
  Web/src/screens/createPostTemplate.js
Labels: Type: Enhancement, Priority: Medium, Status: Completed, Platform: Frontend

#255 Added commenting endpoints, image upload and additional queries
  cmpe451/cmpe451/settings.py
  cmpe451/protopost/models.py
  cmpe451/protopost/serializers.py
  cmpe451/protopost/urls.py
  cmpe451/protopost/views.py
Labels: Priority: High, Platform: Backend

#256 FIX: Added flat representation for comments
  cmpe451/protopost/serializers.py
  cmpe451/protopost/views.py
Labels: Platform: Backend

#238 Mobile yunus styleupdate
  cmpe451-mobile/App.js
  cmpe451-mobile/app/screens/AdvancedSearchScreen.js
  cmpe451-mobile/app/screens/AllCommunitiesScreen.js
  cmpe451-mobile/app/screens/CommunityScreen.js
  cmpe451-mobile/app/screens/CreateCommunityScreen.js
  cmpe451-mobile/app/screens/CreatePostScreen.js
  cmpe451-mobile/app/screens/CreatePostTemplateScreen.js
  cmpe451-mobile/app/screens/FeedScreen.js
  cmpe451-mobile/app/screens/LoginScreen.js
  cmpe451-mobile/app/screens/PostScreen.js
  cmpe451-mobile/app/screens/ProfileScreen.js
  cmpe451-mobile/app/screens/RegisterScreen.js
  cmpe451-mobile/app/screens/UserCommunitiesScreen.js
  cmpe451-mobile/app/screens/UserHome.js
  cmpe451-mobile/app/screens/UserPostsScreen.js
  cmpe451-mobile/app/screens/WelcomeScreen.js
  cmpe451-mobile/package-lock.json
  cmpe451-mobile/package.json
Labels: Type: Enhancement, Priority: High, Platform: Android

#260 Comment functionality added. Location and selection fixed
  Web/src/DATABASE.js
  Web/src/components/card/MaterialUICard.js
  Web/src/components/comment.js
  Web/src/components/commentForm.js
  Web/src/components/googleMaps.js
  Web/src/navigation/Navigation.js
  Web/src/screens/commentPage.js
  Web/src/screens/createPostPage.js
  Web/src/screens/createPostTemplate.js
Labels: Type: Enhancement, Priority: Medium, Status: Completed, Platform: Frontend

#244 Adding Json-LD Header and Readme file for JsonLD and Activity Streams
  cmpe451/Readme.md
  cmpe451/protopost/serializers.py
Labels: Type: Documentation, Priority: Low, Platform: Backend

#263 delete post feature added
  Web/package.json
  Web/src/components/card/MaterialUICard.js
  Web/src/screens/communityPage.js
  Web/src/screens/landingPage.js
  Web/src/screens/myPosts.js
  Web/src/store/actions/communityAction.js
  Web/yarn.lock
Labels: Type: Enhancement, Platform: Frontend

#264 Changed profile mechanism endpoint
  .gitignore
  cmpe451/cmpe451/settings.py
  cmpe451/protopost/models.py
  cmpe451/protopost/serializers.py
  cmpe451/protopost/tests.py
  cmpe451/protopost/urls.py
  cmpe451/protopost/views.py
Labels: Platform: Backend

#266 Profile Page was created and AdvancedSearch was improved
  Web/src/DATABASE.js
  Web/src/components/card/MaterialUICard.js
  Web/src/components/card/SideCard.js
  Web/src/components/navbar/SideBar.js
  Web/src/navigation/Navigation.js
  Web/src/screens/advancedSearchPage.js
  Web/src/screens/communityPage.js
  Web/src/screens/user/profile.js
  Web/src/screens/user/profilePage.js
  Web/src/store/actions/communityAction.js
  Web/src/store/actions/profileAction.js
  Web/src/store/reducers/communityReducer.js
Labels: Type: Enhancement, Priority: High, Platform: Frontend

#270 turned dates into readable format
  Web/package.json
  Web/src/assets/css/communitiesPage.css
  Web/src/components/SearchBar.js
  Web/src/components/card/MaterialUICard.js
  Web/src/screens/allCommunitiesPage.js
  Web/src/screens/myCommunitiesPage.js
  Web/yarn.lock
Labels: Type: Enhancement, Priority: Medium, Status: Completed, Platform: Frontend

#272 Adding all Activity Streams
  .gitignore
  cmpe451/ActivityStream/admin.py
  cmpe451/ActivityStream/apps.py
  cmpe451/ActivityStream/models.py
  cmpe451/ActivityStream/serializers.py
  cmpe451/ActivityStream/tests.py
  cmpe451/ActivityStream/views.py
  cmpe451/cmpe451/settings.py
  cmpe451/protopost/views.py
Labels: Type: Documentation, Priority: High, Status: Completed, Platform: Backend

#273 Added haversine distance calculation for better location query
  cmpe451/protopost/views.py
Labels: Platform: Backend

#274 Comment functions are connected to backend now.
  Web/src/components/card/MaterialUICard.js
  Web/src/components/comment.js
  Web/src/screens/commentPage.js
  Web/src/store/actions/communityAction.js
  Web/src/store/reducers/communityReducer.js
Labels: Type: Enhancement, Priority: Medium, Status: Completed, Platform: Frontend

#276 minor changes
  Web/src/screens/advancedSearchPage.js
  Web/src/store/actions/communityAction.js
  Web/src/store/reducers/communityReducer.js
Labels: Type: Bug, Priority: High, Status: Completed, Platform: Frontend

#275 Removing Junk Files and Unnecessary Imports
  cmpe451/ActivityStream/admin.py
  cmpe451/ActivityStream/apps.py
  cmpe451/ActivityStream/tests.py
  cmpe451/ActivityStream/views.py
  cmpe451/cmpe451/settings.py
  cmpe451/cmpe451/urls.py
  cmpe451/protopost/admin.py
  cmpe451/protopost/apps.py
  cmpe451/protopost/home.py
  cmpe451/protopost/models.py
  cmpe451/protopost/register.py
  cmpe451/protopost/serializers.py
  cmpe451/protopost/tests.py
  cmpe451/protopost/urls.py
  cmpe451/protopost/views.py
Labels: Priority: Medium, Platform: Backend

#277 Added new unit tests for Community,Post,PostTemplate creation and wro…
  .gitignore
  cmpe451/protopost/fixtures/test_db.json
  cmpe451/protopost/tests.py
  cmpe451/protopost/views.py
Labels: Platform: Backend

#278 Adding Backend Test Cases
  cmpe451/protopost/tests.py
Labels: Platform: Backend

#282 Some bugs related to profilescreen was fixed
  Web/src/components/navbar/SideBar.js
  Web/src/navigation/Navigation.js
  Web/src/screens/user/profilePage.js
Labels: Type: Enhancement, Priority: High, Platform: Frontend

#283 For Final Presentation: Merging the frontend code with master branch
  Web/package.json
  Web/src/DATABASE.js
  Web/src/assets/css/communitiesPage.css
  Web/src/components/SearchBar.js
  Web/src/components/card/MaterialUICard.js
  Web/src/components/card/SideCard.js
  Web/src/components/comment.js
  Web/src/components/commentForm.js
  Web/src/components/googleMaps.js
  Web/src/components/navbar/SideBar.js
  Web/src/navigation/Navigation.js
  Web/src/screens/advancedSearchPage.js
  Web/src/screens/allCommunitiesPage.js
  Web/src/screens/commentPage.js
  Web/src/screens/communityPage.js
  Web/src/screens/createPostPage.js
  Web/src/screens/createPostTemplate.js
  Web/src/screens/landingPage.js
  Web/src/screens/myCommunitiesPage.js
  Web/src/screens/myPosts.js
  Web/src/screens/user/profile.js
  Web/src/screens/user/profilePage.js
  Web/src/store/actions/communityAction.js
  Web/src/store/actions/profileAction.js
  Web/src/store/reducers/communityReducer.js
  Web/yarn.lock
Labels: Type: Enhancement, Priority: High, Platform: Frontend

#286 Web bilal profile page bug fix 2
  Web/src/components/navbar/SideBar.js
  Web/src/navigation/Navigation.js
  Web/src/screens/user/profilePage.js
Labels: Type: Enhancement, Priority: High, Platform: Frontend

#288 System manual was written for running Web Application
  Web/src/components/navbar/SideBar.js
  Web/src/navigation/Navigation.js
  Web/src/screens/user/profilePage.js
Labels: Type: Enhancement, Priority: High, Platform: Frontend

#289 System manual was added
  Web/System manual for protopost Web Application.txt
Labels: Type: Enhancement, Priority: High, Platform: Frontend
